[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/admin/*"
  to = "/$1"
  status = 200

[[redirects]]
  from = "/pos/*"
  to = "/$1"
  status = 200

[[redirects]]
  from = "/student/*"
  to = "/$1"
  status = 200
