[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/admin/*"
  to = "/$1"
  status = 200

[[redirects]]
  from = "/pos/*"
  to = "/$1"
  status = 200

[[redirects]]
  from = "/student/*"
  to = "/$1"
  status = 200
